<a href="https://colab.research.google.com/github/alvaro21c/Laboratorio-2023-1/blob/main/Laboratorio3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Funciones
def cuadrado (x,y):
  area=x*y
  return area


In [ ]:
# Probar la funcion
cuadrado (27,27) 
x=25
y=25
print(cuadrado(x,y))

625


In [ ]:
def mayor (x,y):
  ''' Compara dos valores e indica si el primer argumento es mayor o menor que
  el segundo argumento indicando True o False'''
  if x>y:
    return True
  else:
    return False


In [ ]:
help (mayor)

Help on function mayor in module __main__:

mayor(x, y)
    Compara dos valores e indica si el primer argumento es mayor o menor que
    el segundo argumento indicando True o False



In [ ]:
mayor (2,3)

False

In [ ]:
# Crear una funcion agregue en una lista valores unicos.
a= [1,2,2,2,2,2,2,2,3,3,3,3,3,4,5,6]
x=[1,2,3,4,5,6]


# Ayuda
1. Crear x como lista vacia
2. Utilizar una iteracion 
3. La iteracion lo que tiene que hacer es verificar si el elemento ya se encuentra en x o no
4. return x

y in a # esta en la lista
y not in a # no esta en la lista




In [ ]:
# LA LIBRERIA NUMPY
# PERMITE UTILIZAR FUNCIONES DE N/DIMENSIONES QUE COLECCIONA DATOS DE UN MISMO TIPO O DIFERENTE
import numpy as np # importar la lib


In [ ]:
m = np.array([[0,1,2],[3,4,5]]) # 2 filas y 3 columnas
print (m)


[[0 1 2]
 [3 4 5]]


In [ ]:
print (m.shape) # muestra las dimensiones de la matriz

(2, 3)


In [ ]:
print(m[1]) # muestra los elementos de la 2da fila

[3 4 5]


In [ ]:
y = np.array([[0,1,2],[3,4,5],[6,7,8]])
print (y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
print (y[:,2]) # muestra los elementos de la columna 3.

print(y[0:2,1]) # solo extrale la fila 0 y la fila 1 mas la columna 2


print(y[1:,1]) # extrae todas las filas desde 1 y los elementos de la columna 1
 

[2 5 8]
[1 4]
[4 7]


In [ ]:
# matriz de ceros
x = np.zeros((2,2)) # matriz 2x2
print(x)

[[0. 0.]
 [0. 0.]]


In [ ]:
# matriz de puros unos
x = np.ones((2,2)) # matriz 2x2
print (x)

[[1. 1.]
 [1. 1.]]


In [ ]:
x=np.full((2,2),7)  # matriz 2x2
print (x)

[[7 7]
 [7 7]]


In [ ]:
x = np.random.random((2,2))
print (x)

[[0.74207952 0.93307538]
 [0.83275632 0.03177905]]


In [ ]:
# COPIAR Y VINCULAR
x=m # lo que he hecho es vincular la matriz.
print (x)

[[0 1 2]
 [3 4 5]]


In [ ]:
m[0,1]=9
print (m)
print (x)

[[0 9 2]
 [3 4 5]]


In [ ]:
x=m.copy()
print(x)

m[0,1]=1
print(x)

[[0 9 2]
 [3 4 5]]
[[0 9 2]
 [3 4 5]]


In [ ]:
# Operaciones matematicas
# Suma
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print (a+b)
print (np.add(a,b))


[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [ ]:
print (a-b)
print (np.subtract(a,b))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [ ]:
print (a/b)
print (np.divide(a,b))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print (a*b)
print (np.sqrt(a))
print (np.sqrt(b))

[[ 5 12]
 [21 32]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [ ]:
# Reshaping
x=np.arange(8)
print(x)

y=np.reshape(x,(2,4))
print (y)

z=np.array([[0,1],[3,4],[6,7]])
print(z)
b=np.reshape(z,(2,3))
print (b)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [3 4]
 [6 7]]
[[0 1 3]
 [4 6 7]]


In [ ]:
x = np.array([[0,1,2],[3,4,5],[6,7,8]])
#x = np.array([[1,-2,3],[4,5,6],[7,8,-9]])
print(x)
print(x.min())
print(x.max())

print(x.min(axis=0)) # axis 0 es columna, y axis 1 es fila
print(x.max(axis=1)) 



[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
8
[0 1 2]
[2 5 8]


In [ ]:
print(np.sum(x))
print(np.sum(x,axis=1))
print(np.mean(x))
print(np.mean(x,axis=0))
print(np.var(x))

36
[ 3 12 21]
4.0
[3. 4. 5.]
6.666666666666667
